# Generated by Django 2.0.13 on 2019-04-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filedirectory_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedirectory',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='filedirectory',
            name='filepath',
        ),
    ]
