# Generated by Django 2.0.13 on 2019-04-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190428_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedirectory',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
