# Generated by Django 2.0.13 on 2019-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fileviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileviews',
            name='number_of_views',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
