# Generated by Django 2.0.13 on 2019-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190505_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifthandover',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
